### ISSUE TITLE
Introductory presentation

### ISSUE THREAD

**Issue by Beramos** [MichielStock/Julia925#10]
+- 30 min

* filosofie
* voorbeelden van dingen die goed werken in Julia
* Het is geen cursus voor ML in Julia of ABM in Julia way too specific
* ...

**Comment by MichielStock** [comment]
@Beramos @DaanVanHauwermeiren vullen jullie ook die slide aan met je eigen julia projecten?

**Comment by Beramos** [comment]
Maandag

Op za 14 dec. 2019 om 12:48 schreef Michiel Stock <notifications@github.com>

**Comment by DaanVanHauwermeiren** [comment]
@MichielStock Can I have edit access? Thanks!

**Comment by DaanVanHauwermeiren** [comment]
updated my slide!

**Comment by Beramos** [comment]
EPic
