### ISSUE TITLE
missing lib versions in Project.toml

### ISSUE THREAD

**Issue by DaanVanHauwermeiren** [MichielStock/Julia925#15]
missing the versions of:

- ~~julia~~
- ~~Weave~~

**Comment by Beramos** [comment]
Is the Julia version part of the Project.toml environment?

**Comment by MichielStock** [comment]
Do not include Weave, not necessary for the use of the content. 
Consider removing Plots, since it is only used once.

**Comment by DaanVanHauwermeiren** [comment]
I have tested it several times, startup times are lower than 20 seconds. Is it slower on your devices? Maybe it is not necessary to remove Plots?

**Comment by DaanVanHauwermeiren** [comment]
> Is the Julia version part of the Project.toml environment?

Now it is stated that at least Julia version 1 is required. Seems to be ok.

**Comment by Beramos** [comment]
It is fast for me.  Plots is used twice, I don't think it is necessary to remove this. Isn't it necessary for binder?

**Comment by DaanVanHauwermeiren** [comment]
I haven't found anything on "standard libs" that are loaded in binder, so I would keep it.

**Comment by MichielStock** [comment]
Ok

**Comment by DaanVanHauwermeiren** [comment]
I'm going to test all notebooks now to see if everything is fine

**Comment by DaanVanHauwermeiren** [comment]
just for clarity, when using 
`
[compat]
julia = "1"
`
it appears to be using the latest stable relase, which is `1.3`.

Everything seems to be ok, closing issue
