### ISSUE TITLE
Improve plotting of CA

### ISSUE THREAD

**Issue by Beramos** [MichielStock/Julia925#19]

**Comment by MichielStock** [comment]
What would you improve? We can also write a print function for the CA?

Also, I think plotting is really slow in Binder. Maybe we should remove it for those working online?

**Comment by Beramos** [comment]
Ewel het idee was zo’n pretty print of een command line print

Op za 14 dec. 2019 om 12:42 schreef Michiel Stock <notifications@github.com>

**Comment by Beramos** [comment]
Parking this idea for now

**Comment by MichielStock** [comment]
Included in the file
